# Introduction To Numpy

# import Libraries

import numpy as np

In [3]:
list = [1, 2, 3, 4, 5, 6]
print(list)

[1, 2, 3, 4, 5, 6]


In [4]:
array = np.array(list)
print(array)

[1 2 3 4 5 6]


In [7]:
print(len(array))
print(array.ndim)
print(array.shape)

6
1
(6,)


In [8]:
array2 = array.reshape(3,2)
print(array2)

[[1 2]
 [3 4]
 [5 6]]


In [9]:
array2.shape

(3, 2)

In [15]:
x = np.array([[1, 2], [3, 4]], dtype = np.float32)
y = np.array([[5, 6], [7, 8]], dtype = np.float32)
print(x)
print(y)


[[1. 2.]
 [3. 4.]]
[[5. 6.]
 [7. 8.]]


In [16]:
print(x+y)

[[ 6.  8.]
 [10. 12.]]


In [17]:
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]


In [19]:
print(y-x)

[[4. 4.]
 [4. 4.]]
